Fix build issues for meta-intel
install necessary files for intel-ipmi-oem.
this is to fix build issue caused by dependency between
two different repos:

Error:
intel-ipmi-oem/src/sensorcommands.cpp:25:10: fatal error:
phosphor-ipmi-host/utils.hpp: No such file or directory
|  #include <phosphor-ipmi-host/utils.hpp>

Testby: exort TEMPLATECONF=meta-intel/meta-s2600wf/conf/
        bitbake obmc-phosphor-image

Change-Id: I350388a634591151d1cee6c8c7d0aacb98f03bdb
Signed-off-by: Kuiying Wang <kuiying.wang@intel.com>
Signed-off-by: Yong Li <yong.b.li@linux.intel.com>